# -----------------------------------------------------
# GLOBAL settings
# -----------------------------------------------------
global:
  hub: docker.io/istio
  tag: 1.26.6
  istioNamespace: istio-system

# -----------------------------------------------------
# BASE chart
# -----------------------------------------------------
base:
  enabled: true

# -----------------------------------------------------
# ISTIOD settings
# -----------------------------------------------------
istiod:
  pilot:
    autoscaleEnabled: false
    traceSampling: 1.0

  meshConfig:
    enableProtocolSniffingInbound: true
    enableProtocolSniffingOutbound: true

# -----------------------------------------------------
# GATEWAY settings
# -----------------------------------------------------
gateway:
  name: istio-ingressgateway
  enabled: true
  replicaCount: 3

  service:
    type: NodePort
    ports:
      - name: http2
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443

  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 500Mi

  labels:
    app: istio-ingressgateway
    istio: ingressgateway

# -----------------------------------------------------
# CNI settings
# -----------------------------------------------------
cni:
  enabled: true
  cni:
    logLevel: info
