# -----------------------------------------------------
# BASE settings
# -----------------------------------------------------
base:
  enabled: true

# -----------------------------------------------------
# ISTIOD settings
# -----------------------------------------------------
istiod:
  global:
    istioNamespace: istio-system
  pilot:
    autoscaleEnabled: false
    traceSampling: 1.0

# -----------------------------------------------------
# GATEWAY settings
# -----------------------------------------------------
gateway:
  name: istio-ingressgateway
  image:
    repository: docker.io/istio/proxyv2
    tag: 1.26.6
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    ports:
      - name: http2
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443

# Labels for the gateway
  labels:
    app: istio-ingressgateway
    istio: ingressgateway

# -----------------------------------------------------
# CNI settings
# -----------------------------------------------------
cni:
  enabled: true
  cni:
    logLevel: info
