# -----------------------------------------------------
# GLOBAL settings
# -----------------------------------------------------
global:
  hub: docker.io/istio
  tag: 1.26.6
  istioNamespace: istio-system

# -----------------------------------------------------
# BASE chart
# -----------------------------------------------------
base:
  enabled: true

# -----------------------------------------------------
# ISTIOD settings
# -----------------------------------------------------
istiod:
  pilot:
    autoscaleEnabled: false
    traceSampling: 1.0

  meshConfig:
    enableProtocolSniffingInbound: true
    enableProtocolSniffingOutbound: true

# -----------------------------------------------------
# GATEWAY settings
# -----------------------------------------------------
gateway:
  name: istio-ingressgateway

  deployment:
    replicas: 3
    image:
      repository: docker.io/istio/proxyv2
      tag: 1.26.6
      pullPolicy: IfNotPresent

  service:
    type: NodePort
    ports:
      - name: http2
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443

  labels:
    app: istio-ingressgateway
    istio: ingressgateway

# -----------------------------------------------------
# CNI settings
# -----------------------------------------------------
cni:
  enabled: true
  cni:
    logLevel: info
