  cni:
    enabled: true
    provider: default
  

  gatewayClasses:
  istio:
    service:
      type: NodePort  # or NodePort, ClusterIP
    deployment:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 128Mi